version: '3.8'
services:
  elasticsearch:
    container_name: elasticsearch_llm
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.4
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - xpack.security.enrollment.enabled=false
    ports:
      - 9200:9200
    networks:
      - demo-rag
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - es-data:/usr/share/elasticsearch/data
    user: '1000:1000'
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: '1GB'

  kibana:
    image: docker.elastic.co/kibana/kibana:8.11.4
    container_name: kibana_llm
    environment:
      XPACK_ENCRYPTEDSAVEDOBJECTS_ENCRYPTIONKEY: d1a66dfd-c4d3-4a0a-8290-2abcb83ab3aa
    ports:
      - 5601:5601
    networks:
      - demo-rag
    volumes:
      - kibana-data:/usr/share/kibana/data
    user: '1000:1000'
    depends_on:
      - elasticsearch
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

networks:
  demo-rag:
    driver: bridge

volumes:
  es-data:
    driver: local
  kibana-data:
    driver: local
